name: Build Notebook Container
on:
  push:
    branches: [ master, dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@master
    - name: Upload Jupyter
      uses: machine-learning-apps/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        MYBINDERORG_CACHE: true
        MYBINDERORG_TAG: dev
        NOTEBOOK_USER: valhalla
